const PROTOCOLS_SUPPORTING_TLS = ["https", "sftp"];

const SYNCHRONOUS_ENDPOINT_KIND = ["query", "command"];
const ASYNCHRONOUS_ENDPOINT_KIND = ["event"];

export {PROTOCOLS_SUPPORTING_TLS, SYNCHRONOUS_ENDPOINT_KIND, ASYNCHRONOUS_ENDPOINT_KIND}
